#:schema node_modules/wrangler/config-schema.json
name = "tengoping-com"
compatibility_date = "2025-04-01"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[[assets.headers.rules]]
pattern = "*.{css,js}"
[assets.headers.rules.headers]
Cache-Control = "public, max-age=31536000, immutable"

[[assets.headers.rules]]
pattern = "*.{png,jpg,jpeg,gif,webp,avif,svg,ico}"
[assets.headers.rules.headers]
Cache-Control = "public, max-age=31536000, immutable"

[[assets.headers.rules]]
pattern = "/pagefind/*"
[assets.headers.rules.headers]
Cache-Control = "public, max-age=31536000, immutable"

[[assets.headers.rules]]
pattern = "*.woff2"
[assets.headers.rules.headers]
Cache-Control = "public, max-age=31536000, immutable"
